package codetrack.views;

public enum BrowserListenerResponseType {
	LOGIN,
	GET_PROJECT_LIST,
	SET_PROJECT_STATUS,
	SYNC_FULL_PROJECT,
	LOG_OUT,
	ADMIN_GET_GROUP_LIST,
	ADMIN_GET_GROUP_OBSERVATIONS,
	ADMIN_GET_OBSERVATION_PROJECTS,
	ADMIN_DOWNLOAD_PROJECT,
}
